server:
  port: 8100

custom:
  requestCountStartIndex: 0

spring:
  application:
    name: staff-service
  jpa:
    generate-ddl: false
    # 显示SQL
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto: none
    mapping-resources:
  datasource:
    platform: h2
    # 指定DDL脚本
    schema: classpath:schema.sql
    # 指定数据初始化脚本
    data: classpath:data.sql



loggin:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.sinra: DEBUG

